### PR TITLE
fix: handle anonymous callsites. (fixes #5)

### LINKED ISSUE #5: Config displayFilename path.js error
**Describe the bug**
Adding `displayFilename: true` config throw this error:
'"The "path" argument must be of type string"'
Stack error:
```error
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
at assertPath (path.js:39:11)
at Object.basename (path.js:1300:5)
at stack.map.x (/MYAPP/node_modules/signale/signale.js:63:41)
at Array.map (<anonymous>)
at Signale.get filename [as filename] (MYAPP/node_modules/signale/signale.js:63:27)
at Signale._formatFilename (MYAPP/node_modules/signale/signale.js:91:21)
at Signale._meta (MYAPP/node_modules/signale/signale.js:115:22)
at Signale._buildSignale (MYAPP/node_modules/signale/signale.js:142:26)
at Signale._logger (MYAPP/node_modules/signale/signale.js:79:20)
at Object.<anonymous> (MYAPP/src/hooks/logger.js:17:12)
```
**To Reproduce**
Install [feathers.js](https://github.com/feathersjs/feathers).
Replace `winston` by `signale` in `sr/index.js` and `scr/hooks/logger.js`. It's work.
Add this config after `const logger = require('signale');`:
```js
logger.config({
  displayFilename: true
});
```
💥  Boom! 💥 

**Technical Info (please complete the following information)**
 - OS: OSX 10.13.1 (17B1003)
 - Signale Version: ^1.0.1
 - Node.js Version: v9.11.1

### PR DESCRIPTION
**Pull request by jordrake**
Fixes https://github.com/klauscfhq/signale/issues/5 by ensuring we only call path.basename on callsites with a valid file path. The find below should act as a filter of these falsy (usually null from what I've seen) values.

In the unlikely case that there is no suitable file path, set the filename as unknown.

### CODE REVIEW

File: signale.js [hunk 1]
```diff
@@ -62,7 +62,7 @@ class Signale {
     const {stack} = new Error();
     Error.prepareStackTrace = _;
 
-    const callers = stack.map(x => path.basename(x.getFileName()));
+    const callers = stack.map(x => x.getFileName() && path.basename(x.getFileName()));
```
Comment (klauscfhq) [inline signale.js]: By replacing the lines `65`-`66` of `signale.js` with the following:

```js
// signale.js 
// ...
const callers = stack.map(x => x.getFileName()); // L65
console.log(callers); // L66
// ...
```

and then running example of #5 on both node `8.9.1` and `9.11.1`:

```js
// file path: home/signale/foo.js
const signale = require('signale');
signale.config({displayFilename: true});

Promise.resolve().then(() => {
  signale.error('Foo');
});
```
we get these file paths, returned by the callsites:

```js
// Filepaths returned by callsites
[ 'home/signale/foo.js',
  'home/signale/foo.js',
  'home/signale/foo.js',
  'home/signale/foo.js',
  'home/signale/foo.js',
  'home/signale/foo.js',
  null,
  'internal/process/next_tick.js',
  'module.js',
  'bootstrap_node.js' ]
```

Thus, the issue is indeed `path.basename(x.getFileName())`, that crushes once `null`, returned by the `<anonymous>` callsite, is pass to it as an argument. So, instead of returning `unknown`, we can still return the filename `foo.js` just by calling `path.basename` at the end of `filename()`, e.g:

```js
  get filename() {
    const _ = Error.prepareStackTrace;
    Error.prepareStackTrace = (error, stack) => stack;
    const {stack} = new Error();
    Error.prepareStackTrace = _;

    const callers = stack.map(x => x.getFileName()); // Remove path.basename()

    const filePath = callers.find(x => {  // Get the whole filepath
      return x !== callers[0];
    });

    return path.basename(filePath);  // Return the basename
  }
```

It is initial idea, so please feel free to share your thoughts : )

Comment (klauscfhq) [reply signale.js]: I completely agree, we can then change the return statement to something like this: 

```js
return firstExternalFilePath ? path.basename(firstExternalFilePath) : 'unknown';
```

This way even the most extreme cases can be covered and also avoid any potential errors on the way

File: signale.js [hunk 2]
```diff
@@ -62,11 +62,13 @@ class Signale {
...
 
-    const callers = stack.map(x => path.basename(x.getFileName()));
+    const callers = stack.map(x => x.getFileName());
 
-    return callers.find(x => {
+    const firstExternalFilePath = callers.find(x => {
       return x !== callers[0];
     });
+
+    return path.basename(firstExternalFilePath);
```
Comment (klauscfhq) [inline signale.js]: Original comment: https://github.com/klauscfhq/signale/pull/30#discussion_r192074033
```js
return firstExternalFilePath ? path.basename(firstExternalFilePath) : 'anonymous';
```

**Comment by klauscfhq** [comment]
Awesome! : )
