### PR TITLE
Check if Error object has stack property. Fixes #34.

### LINKED ISSUE #34: Logging a SyntaxError crashes signale
**Describe the bug**
Logging an unraised Error causes Signale to explode because it expects a `.stack` property which is `undefined`.

```
TypeError: Cannot read property 'split' of undefined
    at Signale._buildSignale (/home/code/js/armstrong/node_modules/signale/signale.js:163:41)
    at Signale._logger (/home/code/js/armstrong/node_modules/signale/signale.js:81:20)
```

~~According to [MSDN](https://docs.microsoft.com/en-us/scripting/javascript/reference/stack-property-error-javascript), which is linked from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack) as being more relevant for IE **and V8**, the `.stack` property starts out as `undefined`, and is populated only later.~~

~~It seems what I've hit is one of those cases where the `.stack` property isn't set at the time of Signale's processing of the Error.~~

Actually none of that is relevant.

What's happening is that another library is generating a SyntaxError while parsing something else, and not setting the `stack` property.

**To Reproduce**
Make an Error, set `.stack` to `undefined`, give it to Signale:

```js
const { log } = require('signale')
const e = new SyntaxError
e.stack = undefined
log(e)

// TypeError: Cannot read property 'split' of undefined
//    at Signale._buildSignale (/home/code/js/armstrong/node_modules/signale/signale.js:163:41)
//    at Signale._logger (/home/code/js/armstrong/node_modules/signale/signale.js:81:20)
```

**Technical Info (please complete the following information)**
 - OS: Linux
 - Signale Version: 1.1.0
 - Node.js Version: 10.1.0

### PR DESCRIPTION
**Pull request by robertoschiavone**
This PR addresses the problem described in https://github.com/klauscfhq/signale/issues/34

When trying to log an Error with an undefined stack trace, now `signale` correctly logs the error name and ignores the `stack` property.

Before:
```
const [name, ...rest] = msg.stack.split('\n');
                                        ^
TypeError: Cannot read property 'split' of undefined
```

After:
```
✖  error     SyntaxError
```

### CODE REVIEW

**Comment by passcod** [comment]
If you `.toString()` the error instead, and replace the missing stack with that, it avoids losing so much information.

File: signale.js [hunk 1]
```diff
@@ -192,7 +192,7 @@ class Signale {
       }
     }
 
-    if (msg instanceof Error) {
+    if (msg instanceof Error && typeof msg.stack !== 'undefined') {
```
Comment (klauscfhq) [inline signale.js]: Nice approach! We could also rely upon type conversion and prevent any falsy value from making it through, that way rare cases where `stack` is set, for example, to `null` are too covered;

```js
if (msg instanceof Error && msg.stack) {
```

**Comment by robertoschiavone** [comment]
@passcod can you provide an example of that? I tried to reproduce your `.toString()` suggestion but I obtained the exact same results.

Obviously this is the smallest tweak ever committed, so I guess that any further improvement would be welcome.

**Comment by klauscfhq** [comment]
Thank you!

**Comment by passcod** [comment]
@robertoschiavone ah, nevermind, yes you're correct
